version: "3.8"

volumes:
  postgres2_data:
  postgres1_data:
  rabbitmq_data:

services:
  gateway:
    image: gateway:latest
    build:
      context: gateway/
    ports:
      - "8080:8080"
    # depends_on:
    #   - cart
    #   - checkout
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # cart:
  #   image: cart:latest
  #   build:
  #     context: cart/
  #   expose:
  #     - "8081"
  #   healthcheck:
  #     test: ["CMD", "curl", "--fail", "http://localhost:8081/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s
  #   environment:
  #     WAIT_HOSTS: postgres-cart:5432
  #     DB_USER_AUTH: ${DB_USER_AUTH}
  #     DB_PASSWORD_AUTH: ${DB_PASSWORD_AUTH}
  #     DB_URI_AUTH: ${DB_URI_AUTH_CHECKOUT}

  # checkout:
  #   image: checkout:latest
  #   build:
  #     context: checkout/
  #   expose:
  #     - "8082"
  #   healthcheck:
  #     test: ["CMD", "curl", "--fail", "http://localhost:8082/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s
  #   environment:
  #     WAIT_HOSTS: postgres-checkout:5433
  #     DB_USER_AUTH: ${DB_USER_AUTH}
  #     DB_PASSWORD_AUTH: ${DB_PASSWORD_AUTH}
  #     DB_URI_AUTH: ${DB_URI_AUTH_CHECKOUT}

  postgres-checkout:
    container_name: postgres-checkout
    image: postgres:16.3-alpine3.20

    environment:
      POSTGRES_DB: checkout_db
      POSTGRES_USER: ${DB_USER_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
      PGDATA: "/data/postgres"
      PGPORT: 5433

    volumes:
      - postgres2_data:/var/lib/postgresql/data

    ports:
      - "5433:5433"
    restart: unless-stopped

  postgres-cart:
    container_name: postgres-cart
    image: postgres:16.3-alpine3.20

    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: ${DB_USER_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
      PGDATA: "/data/postgres"
      PGPORT: 5432

    volumes:
      - postgres1_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
