server:
  port: 8081

spring:
  application:
    name: cart
  datasource:
    url: jdbc:postgresql://postgres-cart:5432/cart_db
    username: user
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect